<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <link href='http://a1.4ormat.com/theme_versions/332683/assets/stylesheets/font-awesome.min.css' media='screen' rel='stylesheet' type='text/css' />
    <!--[if lt IE 9]>
      <link href='http://a1.4ormat.com/theme_versions/332683/assets/stylesheets/ie8.css' media='screen' rel='stylesheet' type='text/css' />
    <![endif]-->
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
    
<script type='text/javascript'>
try{function css_browser_selector(u){var ua=u.toLowerCase(),is=function(t){return ua.indexOf(t)>-1},g='gecko',w='webkit',s='safari',o='opera',m='mobile',h=document.documentElement,b=[(!(/opera|webtv/i.test(ua))&&/msie\s(\d)/.test(ua))?('ie ie'+RegExp.$1):is('firefox/2')?g+' ff2':is('firefox/3.5')?g+' ff3 ff3_5':is('firefox/3.6')?g+' ff3 ff3_6':is('firefox/3')?g+' ff3':is('gecko/')?g:is('opera')?o+(/version\/(\d+)/.test(ua)?' '+o+RegExp.$1:(/opera(\s|\/)(\d+)/.test(ua)?' '+o+RegExp.$2:'')):is('konqueror')?'konqueror':is('blackberry')?m+' blackberry':is('android')?m+' android':is('chrome')?w+' chrome':is('iron')?w+' iron':is('applewebkit/')?w+' '+s+(/version\/(\d+)/.test(ua)?' '+s+RegExp.$1:''):is('mozilla/')?g:'',is('j2me')?m+' j2me':is('iphone')?m+' iphone':is('ipod')?m+' ipod':is('ipad')?m+' ipad':is('mac')?'mac':is('darwin')?'mac':is('webtv')?'webtv':is('win')?'win'+(is('windows nt 6.0')?' vista':''):is('freebsd')?'freebsd':(is('x11')||is('linux'))?'linux':'','js']; c = b.join(' '); h.className += ' '+c; return c;}; css_browser_selector(navigator.userAgent);}catch(e){}
</script>
<!-- fonts -->

  
    <script src="//use.edgefonts.net/cabin.js"></script>
  

  

  


<title>El Roi Photography - raw</title>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
<link href='/static/default_favicon.png' rel='shortcut icon' />
<link href='/static/default_favicon.png' rel='icon' />
<meta content='' name='current_path' />
<meta content='true' name='protect_images' />
<meta content='Javier Edwards © 2013 All Rights Reserved' name='image_protection_blurb' />
<meta content='Gainesville Florida  fashion, wedding, portraiture, lifestyle and event photographer' name='description' />
<meta content='wedding, photography, el roi photography, elroiphoto, el roi blog, Javier Edwards, Spirit of Faith Christian Center, Kenneth Claytor, wedding, portraits, editorial, photojournalism, what does el roi mean?, God, Jesus, Christ, Jesus Christ, UF, Javier edwa' name='keywords' />

<meta property="og:site_name" content="El Roi Photography"/>
<meta property="og:title" content="El Roi Photography - raw"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="http://elroiphoto.4ormat.com/raw"/>
<meta property="og:image" content="http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x150.gif"/>



<link href='/static/theme_api/v1/share_panel.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/static/theme_api/v1/font-awesome.min.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/static/theme_api/v1/theme_social.css' media='screen' rel='stylesheet' type='text/css' />
<!--[if IE 7]>
<link rel="stylesheet" href="/static/theme_api/v1/theme_social-ie7.css">
<![endif]-->
<!--[if IE 8]>
<link rel="stylesheet" href="/static/theme_api/v1/theme_social-ie7.css">
<![endif]-->




<link href='http://elroiphoto.4ormat.com/stylesheet.css' media='screen' rel='stylesheet' type='text/css' /> <!-- NOTE: this is what is generated by the theme CSS template -->









<style type='text/css'>
.youtube_cont.preview, .vimeo_cont.preview{position:relative;}
.youtube_cont.preview img, .vimeo_cont.preview img{width: 100%; height: 100%; z-index: 1; position: absolute; left: 0;}
.youtube_cont.preview .load_iframe, .vimeo_cont.preview .load_iframe{left: 0; position: absolute; width: 100%; height: 100%; background-repeat: no-repeat; background-position: center center; background-image: url('/static/vid_overlay.png'); z-index: 2;}
.youtube_cont.preview iframe, .vimeo_cont.preview iframe{left: 0; position: absolute; width: inherit; height: inherit; z-index: 1000;}
</style>

    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/jquery.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/jquery.smartresize.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/jquery.jscrollpane.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/jquery.supersized.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/supersized.custom.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/32683/assets/javascripts/fastclick.js" type="text/javascript"></script>
    <script src="http://a1.4ormat.com/theme_versions/332683/assets/javascripts/theme.js" type="text/javascript"></script>
  </head>
  <body class="page_10846 gallery no-touch"><!-- BOTTOM BAR -->
    <div id="bottom_bar">
      <div id="logo">
        
        <a href="/">
          <img src="http://a3.4ormat.com/vfs/8345/thumbs/2644469/960x0.gif">
        </a>
        
      </div>
      <nav>
        <ul id="menu" class="menu_list">
          
             
          <li class="category top_level">
            <a href="#" class="category_name">Documentary</a>
            <ul class="dropdown">
              
              <li class="item ">
                <a href='/photojournalism' >Singles</a>
              </li>
              
              <li class="item ">
                <a href='/photo-story' >Photo Story</a>
              </li>
              
            </ul>
          </li>
          
           
             
          <li class="category top_level">
            <a href="#" class="category_name">Portraiture</a>
            <ul class="dropdown">
              
              <li class="item ">
                <a href='/editorial' >Commercial </a>
              </li>
              
              <li class="item ">
                <a href='/galleries' >Project Gallery </a>
              </li>
              
              <li class="item ">
                <a href='/wedding-gallery' >Wedding Gallery</a>
              </li>
              
              <li class="item ">
                <a href='/recent' >Recent Work</a>
              </li>
              
            </ul>
          </li>
          
           
             
          <li class="category top_level">
            <a href="#" class="category_name">Commissioned </a>
            <ul class="dropdown">
              
              <li class="item ">
                <a href='/music' > Music </a>
              </li>
              
              <li class="item ">
                <a href='/themachine' >Lush Longbaords: The Machine</a>
              </li>
              
              <li class="item ">
                <a href='/uf-levin-college-of-law-diversity-packa' >Levin College of Law: Diversity Pack</a>
              </li>
              
            </ul>
          </li>
          
           
             
          <li class="category top_level">
            <a href="#" class="category_name">Multimedia</a>
            <ul class="dropdown">
              
              <li class="item ">
                <a href='/media' >Gallery</a>
              </li>
              
            </ul>
          </li>
          
           
             
          <li class="category top_level">
            <a href="#" class="category_name">Info</a>
            <ul class="dropdown">
              
              <li class="item ">
                <a href='/splash' >Home</a>
              </li>
              
              <li class="item ">
                <a href='/about' >About</a>
              </li>
              
              <li class="item ">
                <a href='/646331-contact' >Contact</a>
              </li>
              
              <li class="item ">
                <a href='/resume' >Resume</a>
              </li>
              
            </ul>
          </li>
          
           
        </ul>
      </nav>
      <!-- SOCIAL ICONS -->
      <aside class="social_icons">
        
        <ul>
          
            
                
                  <li class="icon-instagram social_icon">
                    <a href="http://instagram.com/elroiphoto#" target="_blank">http://instagram.com/elroiphoto#</a>
                  </li>
                
              
          
            
                
                  <li class="icon-facebook social_icon">
                    <a href="https://www.facebook.com/pages/El-Roi-Photography/163475770384672" target="_blank">https://www.facebook.com/pages/El-Roi-Photography/163475770384672</a>
                  </li>
                
              
          
            
                
                  <li class="icon-tumblr social_icon">
                    <a href="http://elroiphoto.tumblr.com/" target="_blank">http://elroiphoto.tumblr.com/</a>
                  </li>
                
              
          
            
                
                  <li class="icon-twitter social_icon">
                    <a href="www.elroiphoto-blog.com" target="_blank">www.elroiphoto-blog.com</a>
                  </li>
                
              
          
            
                
            
          
        </ul>
        
        
          <a href="#" class="item icon_share social_icon" id="share_4ormat_link">Share</a>
        
      </aside><!-- END SOCIAL ICONS -->
      
      <!-- <span id="thumb-icon">&#xe008;</span> -->
      <div id="thumb-tray">
        <div id="thumb-background"></div>
      </div>
      
      <div id="bottom_bar_background"></div>
    </div><!-- END BOTTOM BAR-->

    
    <div id="thumbs_show"></div>
    
    <div class="slide_nav">
      
        <a id="prev_slide" class="slide_button load-item">&#xe001;</a>
        <a id="next_slide" class="slide_button load-item">&#xe002;</a>
      
    </div>
    <!--Navigation-->
    <a href="#" id="captionToggle"></a> 
    <div id="caption">&nbsp;</div>
  <footer> 
    
<!-- -->



  <div id='using'>
    <span>Using</span>
    <a title='Online Portfolio Website' alt='4ormat Online Portfolio Website' href='http://4ormat.com/l/your_portfolio'>4ormat</a>
  </div>

  <style type="text/css">
    b { font-weight: bold; }
    i { font-style: italic; }
    #using { 
      opacity: 1!important;
      position: fixed!important;
      z-index: 2147483647!important;
      
        color: #666666!important;
      
      font-size: 10px;
      font-family: verdana, Arial, sans-serif!important;
      display:block!important;
      
        
          bottom: 8px!important;
        
      
      
        
          right: 8px!important;
        
      
      word-spacing: 0px!important;
    }
    #using a {
      opacity: 1!important;
      z-index: 2147483647!important;
      display:inline!important;
      position:static!important;
      text-decoration: underline!important;
      
        color: #666666!important;
      
    }
    #using a:hover { 
      color:red!important;
      text-decoration: underline!important;
    }
  </style>


<style type="text/css">
  /* Image Protection */
  #image_protection_notice {
    color: #000;
    padding: 8px 8px;
    width: 200px;
    font-size: 11px;
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px; 
    background: #fff;
    box-shadow: 0 0 5px #222;
    -webkit-box-shadow: 0 0 5px #222;
    -moz-box-shadow: 0 0 5px #222;
    box-shadow: 0 0 5px #222
  }
</style>

<script type='text/javascript'>
  //<![CDATA[
    var _4ORMAT_DATA = {"site":{"url":"http://elroiphoto.4ormat.com","fav_icon_url":"/static/default_favicon.png","meta_description":"Gainesville Florida  fashion, wedding, portraiture, lifestyle and event photographer","meta_keywords":"wedding, photography, el roi photography, elroiphoto, el roi blog, Javier Edwards, Spirit of Faith Christian Center, Kenneth Claytor, wedding, portraits, editorial, photojournalism, what does el roi mean?, God, Jesus, Christ, Jesus Christ, UF, Javier edwa","name":"El Roi Photography","user_google_analytics_key":"UA-34563273-1","system_google_analytics_key":"UA-11743039-2","protect_images":true,"image_protection_blurb":"Javier Edwards © 2013 All Rights Reserved","hide_using_4ormat":false},"theme":{"background_color":"#ffffff","logo_typography":{"color":"#414042","font-family":"cabin, sans-serif","font-size":"10","font-style":"normal","font-weight":"normal"},"logo_image":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/960x0.gif","logo_text":"Commercial // Editorial // Documentary Photography","text_typography":{"color":"#414042","font-family":"cabin, sans-serif","font-size":"12","font-weight":"normal"},"background_text_color":"#E5E5E5","link_typography":{"color":"#414042","text-decoration":"underline","font-style":"normal","font-weight":"normal","hover":{"color":"#414042","text-decoration":"underline"}},"headline_typography":{"color":"#414042","font-family":"cabin, sans-serif","font-size":"14","font-style":"normal","font-weight":"normal"},"bottom_bar_height":"Normal","background_bottom_bar":"#fffcfc","menu_item_typography":{"color":"#414042","font-family":"\"Courier New\", Menlo, monospace","font-size":"14","font-style":"normal","font-weight":"normal","hover":{"background":"#ffffff","color":"#414042"},"selected":{"color":"#000000"}},"menu_category_typography":{"background":"#ffffff","color":"#414042","font-style":"normal","font-weight":"normal","hover":{"background":"#ffffff","color":"#000000"},"selected":{"background":"#ffffff","color":"#000000"}},"fullscreen_images":false,"gallery_scrollbar_color":"#878e93","gallery_navigation_typography":{"background":"#ffffff","color":"#000000"},"gallery_navigation_frame_type":"Round","slide_transition":"Fade","slide_transition_speed":"Regular","gallery_caption_typography":{"background":"#ffffff","color":"#000000","font-family":"\"Courier New\", Menlo, monospace","font-size":"12"},"gallery_captions_visibility":false,"gallery_video_caption_alignment":"Top","gallery_thumb_tray":true,"gallery_thumb_shape":"Original","gallery_thumb_border":"#474747","thumbs_icon_color":"#ffffff","thumbs_spacing":"Medium","thumbs_height":"Medium","listing_caption_typography":{"color":"#414042","font-family":"\"Courier New\", Menlo, monospace","font-size":"12","font-style":"normal","font-weight":"normal"},"share_button_typography":{"background":"#E5E5E5","color":"#000000","hover":{"background":"#1f1c1c","color":"#ffffff"}},"show_social_sharing":true,"social_icon_typography":{"color":"#000000","hover":{"color":"#000000"}},"icon1":"Instagram","twitter":"http://instagram.com/elroiphoto#","icon2":"Facebook","facebook":"https://www.facebook.com/pages/El-Roi-Photography/163475770384672","icon3":"Tumblr","linkedin":"http://elroiphoto.tumblr.com/","icon4":"Twitter","icon4text":"www.elroiphoto-blog.com","icon5":"None","icon5text":null,"logo_image_thumbnails":{"200x200":{"width":200,"height":200,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/200x200.gif"},"0x150":{"width":212,"height":150,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/0x150.gif"},"960x0":{"width":500,"height":353,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/960x0.gif"},"0x400":{"width":500,"height":353,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/0x400.gif"},"300x0":{"width":300,"height":212,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/300x0.gif"},"1600x1200":{"width":500,"height":353,"src":"http://a3.4ormat.com/vfs/8345/thumbs/2644469/1600x1200.gif"}}},"asset_base_path":"http://a1.4ormat.com/theme_versions/332683/assets/","menu_items":[{"id":73625,"type":"category","name":"Documentary","pages":[{"id":60682,"type":"gallery","name":"Singles","href":"/photojournalism","open_in_new_window":true},{"id":631285,"type":"listing","name":"Photo Story","href":"/photo-story","open_in_new_window":null}]},{"id":73626,"type":"category","name":"Portraiture","pages":[{"id":396249,"type":"gallery","name":"Commercial ","href":"/editorial","open_in_new_window":true},{"id":392915,"type":"listing","name":"Project Gallery ","href":"/galleries","open_in_new_window":null},{"id":724492,"type":"listing","name":"Wedding Gallery","href":"/wedding-gallery","open_in_new_window":null},{"id":448709,"type":"gallery","name":"Recent Work","href":"/recent","open_in_new_window":true}]},{"id":97104,"type":"category","name":"Commissioned ","pages":[{"id":1048667,"type":"gallery","name":" Music ","href":"/music","open_in_new_window":true},{"id":1024232,"type":"gallery","name":"Lush Longbaords: The Machine","href":"/themachine","open_in_new_window":true},{"id":1027187,"type":"gallery","name":"Levin College of Law: Diversity Pack","href":"/uf-levin-college-of-law-diversity-packa","open_in_new_window":true}]},{"id":19619,"type":"category","name":"Multimedia","pages":[{"id":397313,"type":"gallery","name":"Gallery","href":"/media","open_in_new_window":true}]},{"id":19620,"type":"category","name":"Info","pages":[{"id":471067,"type":"content","name":"Home","href":"/splash","open_in_new_window":true},{"id":812112,"type":"content","name":"About","href":"/about","open_in_new_window":true},{"id":646331,"type":"content","name":"Contact","href":"/646331-contact","open_in_new_window":true},{"id":833669,"type":"gallery","name":"Resume","href":"/resume","open_in_new_window":true}]}],"page":{"id":1084615,"type":"gallery","layout":"vertical","name":"raw","any_asset_copy":false,"assets":[{"id":9186566,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/900x0.gif","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/700x0.gif","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/550x0.gif","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/400x0.gif","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/300x0.gif","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x900.gif","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x700.gif","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x550.gif","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x400.gif","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x300.gif","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/300x300.gif","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/200x200.gif","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/100x100.gif","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/150x0.gif","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x150.gif","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/200x135.gif","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/1600x1200.gif","image_dimensions_1600x1200":[1800,1200]},{"id":9186565,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/900x0.jpg","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/700x0.jpg","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/550x0.jpg","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/400x0.jpg","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/300x0.jpg","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x900.jpg","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x700.jpg","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x550.jpg","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x400.jpg","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x300.jpg","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/300x300.jpg","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/200x200.jpg","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/100x100.jpg","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/150x0.jpg","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/0x150.jpg","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/200x135.jpg","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a3.4ormat.com/vfs/8345/thumbs/6249314/1600x1200.jpg","image_dimensions_1600x1200":[1800,1200]},{"id":9186563,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/900x0.jpg","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/700x0.jpg","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/550x0.jpg","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/400x0.jpg","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/300x0.jpg","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x900.jpg","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x700.jpg","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x550.jpg","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x400.jpg","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x300.jpg","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/300x300.jpg","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/200x200.jpg","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/100x100.jpg","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/150x0.jpg","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/0x150.jpg","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/200x135.jpg","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a1.4ormat.com/vfs/8345/thumbs/6249312/1600x1200.jpg","image_dimensions_1600x1200":[1800,1200]},{"id":9186552,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/900x0.jpg","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/700x0.jpg","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/550x0.jpg","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/400x0.jpg","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/300x0.jpg","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x900.jpg","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x700.jpg","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x550.jpg","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x400.jpg","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x300.jpg","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/300x300.jpg","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/200x200.jpg","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/100x100.jpg","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/150x0.jpg","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/0x150.jpg","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/200x135.jpg","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a2.4ormat.com/vfs/8345/thumbs/6249475/1600x1200.jpg","image_dimensions_1600x1200":[1800,1200]},{"id":9186550,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/900x0.jpg","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/700x0.jpg","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/550x0.jpg","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/400x0.jpg","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/300x0.jpg","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x900.jpg","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x700.jpg","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x550.jpg","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x400.jpg","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x300.jpg","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/300x300.jpg","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/200x200.jpg","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/100x100.jpg","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/150x0.jpg","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/0x150.jpg","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/200x135.jpg","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a2.4ormat.com/vfs/8345/thumbs/6249298/1600x1200.jpg","image_dimensions_1600x1200":[1800,1200]},{"id":9186559,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/900x0.jpg","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/700x0.jpg","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/550x0.jpg","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/400x0.jpg","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/300x0.jpg","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x900.jpg","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x700.jpg","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x550.jpg","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x400.jpg","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x300.jpg","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/300x300.jpg","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/200x200.jpg","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/100x100.jpg","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/150x0.jpg","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/0x150.jpg","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/200x135.jpg","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a3.4ormat.com/vfs/8345/thumbs/6249308/1600x1200.jpg","image_dimensions_1600x1200":[1800,1200]},{"id":9186557,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/900x0.JPG","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/700x0.JPG","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/550x0.JPG","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/400x0.JPG","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/300x0.JPG","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x900.JPG","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x700.JPG","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x550.JPG","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x400.JPG","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x300.JPG","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/300x300.JPG","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/200x200.JPG","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/100x100.JPG","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/150x0.JPG","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/0x150.JPG","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/200x135.JPG","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a1.4ormat.com/vfs/8345/thumbs/6249306/1600x1200.JPG","image_dimensions_1600x1200":[1800,1200]},{"id":9186976,"type":"image","copy_alignment":"none","copy":null,"width":0,"copy_width":0,"scaled_image_width":0,"tag":null,"image_url_900x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/900x0.gif","image_dimensions_900x0":[900,600],"image_url_700x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/700x0.gif","image_dimensions_700x0":[700,467],"image_url_550x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/550x0.gif","image_dimensions_550x0":[550,367],"image_url_400x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/400x0.gif","image_dimensions_400x0":[400,267],"image_url_300x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/300x0.gif","image_dimensions_300x0":[300,200],"image_url_0x900":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x900.gif","image_dimensions_0x900":[1350,900],"image_url_0x700":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x700.gif","image_dimensions_0x700":[1050,700],"image_url_0x550":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x550.gif","image_dimensions_0x550":[825,550],"image_url_0x400":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x400.gif","image_dimensions_0x400":[600,400],"image_url_0x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x300.gif","image_dimensions_0x300":[450,300],"image_url_300x300":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/300x300.gif","image_dimensions_300x300":[300,300],"image_url_200x200":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/200x200.gif","image_dimensions_200x200":[200,200],"image_url_100x100":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/100x100.gif","image_dimensions_100x100":[100,100],"image_url_150x0":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/150x0.gif","image_dimensions_150x0":[150,100],"image_url_0x150":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/0x150.gif","image_dimensions_0x150":[225,150],"image_url_200x135":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/200x135.gif","image_dimensions_200x135":[200,135],"image_url_1600x1200":"http://a3.4ormat.com/vfs/8345/thumbs/6249608/1600x1200.gif","image_dimensions_1600x1200":[1800,1200]}],"content_page_assets":{},"columns":[],"title":null,"image_width":null,"layout_options":null,"category_id":null,"content_page_template_name":null,"dependencies":{"fonts":{"adobe":{"url":"//use.edgefonts.net/cabin.js"}}},"content_editable":false},"paths":{"root":"/","theme_stylesheet":"http://elroiphoto.4ormat.com/stylesheet.css"},"meta":{"api_version":1,"authorized":true,"form_authenticity_token":"ksMc1C+gpGLoaG0o2sEojOtb8PwJxujZTWUm29bLFCg=","fb_url":"http://elroiphoto.4ormat.com/raw","fb_image":"http://a2.4ormat.com/vfs/8345/thumbs/6249244/0x150.gif","theme_version":18,"theme_name":"Sun","profession_identifier":565,"country_identifier":886,"using":{"bottom":8,"right":8},"explicit":false,"mobile":{}}};
  //]]>
</script>
<script src='/static/theme_api/v1/ZeroClipboard.js' type='text/javascript'></script>
<script src='/static/theme_api/v1/4ormat-6eeed9318db0e0cf49f0a4ca29a618f7.js' type='text/javascript'></script>






<script type="text/javascript">
  var _gaq = _gaq || [];
  
    _gaq.push(['_setAccount', 'UA-11743039-2']); 
    
      
      _gaq.push(['_setCustomVar', 1, 'theme_name', 'Sun', 3]);
      _gaq.push(['_setCustomVar', 2, 'theme_version', '18', 3]);
      _gaq.push(['_setCustomVar', 3, 'profession', '565', 3]);
      _gaq.push(['_setCustomVar', 4, 'country_identifier', '886', 3]);
    
    _gaq.push(['_trackPageview']);
  
  
    _gaq.push(['t2._setAccount', 'UA-34563273-1']); _gaq.push(['t2._trackPageview']);
  
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>


<!-- -->

  </footer>
</body>
</html>